### ISSUE TITLE
[ENH] More plotting

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/tractr#10]
A function that takes a dataset and plots the data laid out in anatomically- (similar to [this function](https://github.com/yeatmanlab/AFQ-Insight/blob/main/afqinsight/plot.py#L54) in AFQ-Insight). Maybe @kellychang4 would like to take this on? She recently showed me something like this in a dataset we're working on together. This would presumably go into plot.R

**Comment by kellychang4** [comment]
Closed with https://github.com/yeatmanlab/tractr/pull/14
