### ISSUE TITLE
Combining different plots into one single figure

### ISSUE THREAD

**Issue by SendyCaffarra** [yeatmanlab/tractr#2]
**Is your feature request related to a problem? Please describe.**

Combining subplots into a figure

**Describe the solution you'd like**

Here is what I did to put different plots together in R
cowplot::plot_grid(plot, tbl, nrow = 1, ncol = 2, rel_widths = c(3, 1) ) 
where plot was a ggplot output and tbl was a table made with tableGrob but I guess it should work with different types of plots/tables

**Comment by kellychang4** [comment]
There is also the [patchwork](https://patchwork.data-imaginist.com/) package that combines ggplots.

**Comment by kellychang4** [comment]
Was there a desired code solution for this issue?

**Comment by arokem** [comment]
I don't think this is a tractr-specific issue, and may already be handled by the new tract_profiles visualization function. Please reopen if you disagree.
