### ISSUE TITLE
Potential name collision

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/tractr#24]
[This software library](https://github.com/tractor/tractor) precedes ours by several years and seems under active development. To avoid confusion, and at the risk of spending the rest of today on a bike-shedding discussion, we might want to choose a different name. How about "rAFQ" (pronoounced ray-eff-cue)?

**Comment by richford** [comment]
I love a good bike-shed. This might not be a very popular recommendation but what about a more whimsical name that doesn't include tract, fiber, or AFQ but rather alludes to the spaghettome inside our skulls:

[Pici](https://en.wikipedia.org/wiki/Pici) (pronounced like peachy) is a hand-rolled pasta like thick spaghetti.

Could be fun!

**Comment by richford** [comment]
I'm also thinking it might not be so bad to stick with "tractr" and just rely on the difference with spelling.

**Comment by arokem** [comment]
I would be a bit annoyed if I was the author of the tractor package.

**Comment by arokem** [comment]
I like "tractable" (which came up in a slack conversation)
