### ISSUE TITLE
[ENH] Automatic Package Website

### ISSUE THREAD

**Issue by kellychang4** [yeatmanlab/tractr#42]
Incorporate GitHub Action to publish a package website automatically. 
Something like this? [https://r-pkgs.org/website.html](https://r-pkgs.org/website.html)

**Comment by arokem** [comment]
Like what? I think maybe a link is missing?

**Comment by kellychang4** [comment]
Added!

**Comment by arokem** [comment]
Maybe this? https://github.com/marketplace/actions/r-pkgdown-multi-version-docs

**Comment by arokem** [comment]
`Rscript -e "pkgdown::build_site()"` builds a nice version of html docs for me locally, so this seems promising. I'll try to make a PR with this.

**Comment by arokem** [comment]
This is closed through #46, #43
